### ISSUE TITLE
release interval changes not saved

### ISSUE THREAD

**Issue by neogeographica** [xurble/recast#28]
No idea if this is the same issue as #23 ...

On the feed edit page, I use the pulldown to change the release interval. With the Firefox dev tools I can see the POST to the feed URL delivering the requested "frequency" value and getting a 200 status.

However if I close and re-open the feed edit page it shows the old release interval.

**Comment by xurble** [comment]
Could you post en example feed where this is happening, what you've changed the frequency to and what frequency you're seeing when you go back to it?

**Comment by neogeographica** [comment]
Sure, for example http://recastthis.com/feed/edit/0a2b6c5e-db74-41ea-9e96-7678b2f41683/ I see with a 6 day interval. Change it to 8 in the dropdown. After a while I close that tab, open the URL in a new tab... it shows as interval 6.

**Comment by neogeographica** [comment]
...and now I see 8. Just a big lag time on taking up the change?

**Comment by xurble** [comment]
I think it might be a caching issue. It doesn't happen for me. If you have more than one browser, you could try changing it and then immediately looking at it in the other browser.

**Comment by neogeographica** [comment]
I'm going to redact the link in my comment above, just so it's not laying out there for anyone to mess with.

**Comment by xurble** [comment]
This should be fixed now

**Comment by neogeographica** [comment]
Looks good! Thank you.
